version: '3'

services:
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./producer:/usr/src/app
    networks:
      - app-network
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
    links:
      - rabbitmq

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./consumer:/usr/src/app
    networks:
      - app-network
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
